package com.agentdev.agent.base;

import com.agentdev.agent.review.ReviewService;
import com.agentdev.client.github.GitHubClientService;
import com.agentdev.client.jira.JiraClient;
import com.agentdev.core.model.*;
import com.agentdev.docker.DockerClaudeRunner;
import com.agentdev.git.GitService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;

public abstract class BaseAgentService {
    
    private static final Logger log = LoggerFactory.getLogger(BaseAgentService.class);

    @Autowired protected JiraClient          jiraClient;
    @Autowired protected GitService          gitService;
    @Autowired protected DockerClaudeRunner  dockerRunner;
    @Autowired protected GitHubClientService gitHubClient;
    @Autowired protected ReviewService       reviewService;

    protected abstract String getJiraLabel();
    protected abstract String getTargetRepo();
    protected abstract String buildPrompt(JiraIssue ticket);

    protected void postProcess(String repoPath, JiraIssue ticket) {}

    public void processTicket(JiraIssue ticket) {
        String branch   = "agent/" + ticket.key().toLowerCase();
        String repoPath = null;

        try {
            if (gitHubClient.branchExists(getTargetRepo(), branch)) {
                log.info("Branch {} already exists, skipping", branch);
                return;
            }

            jiraClient.transitionIssue(ticket.key(), "In Progress");
            repoPath = gitService.cloneAndBranch(getTargetRepo(), branch);

            ClaudeCodeResult result = dockerRunner.run(repoPath, buildPrompt(ticket));
            if (!result.success()) { handleFailure(ticket, result); return; }

            postProcess(repoPath, ticket);

            ReviewDecision review = reviewService.review(ticket, gitService.getDiff(repoPath));

            if (review.status() == ReviewStatus.NEEDS_REVISION) {
                log.info("Revision requested for {} — retrying", ticket.key());
                dockerRunner.run(repoPath, buildRevisionPrompt(ticket, review));
                review = reviewService.review(ticket, gitService.getDiff(repoPath));
            }

            if (review.status() == ReviewStatus.APPROVED) {
                gitService.commitAndPush(repoPath,
                    ticket.key() + ": " + ticket.summary(), branch);
                PullRequestResult pr = gitHubClient.openPullRequest(
                    getTargetRepo(),
                    ticket.key() + ": " + ticket.summary(),
                    branch,
                    buildPrBody(ticket, review));
                jiraClient.transitionIssue(ticket.key(), "In Review");
                jiraClient.addComment(ticket.key(), "PR opened: " + pr.url());
            } else {
                handleFailure(ticket, result);
            }

        } finally {
            if (repoPath != null) gitService.cleanup(repoPath);
        }
    }

    private void handleFailure(JiraIssue ticket, ClaudeCodeResult result) {
        jiraClient.transitionIssue(ticket.key(), "Failed");
        jiraClient.addComment(ticket.key(),
            "Agent failed after retry. Manual implementation required.\n"
            + "Exit code: " + result.exitCode());
    }

    private String buildRevisionPrompt(JiraIssue ticket, ReviewDecision review) {
        return buildPrompt(ticket)
            + "\n\nYOUR PREVIOUS ATTEMPT WAS REJECTED. Fix these specific issues:\n"
            + String.join("\n", review.issues())
            + "\n\nSuggested fixes:\n"
            + String.join("\n", review.suggestions());
    }

    private String buildPrBody(JiraIssue ticket, ReviewDecision review) {
        return "Resolves " + ticket.key()
            + "\n\n" + ticket.description()
            + "\n\n**Review summary:** " + review.summary()
            + "\n\n_Generated by Agent Bot_";
    }
}
